version: "3"
services:

  # ┏━ NextJS | A framework for the web.
  app:
    image: node:18-alpine
    restart: unless-stopped
    command: ["yarn", "deploy"]
    ports: [$APP_PORT:3000]
    depends_on: [database]
    working_dir: /usr/app
    volumes: [.:/usr/app]
    profiles: ["prod"]
    env_file: .env
